version: "3"
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./backend/db:/data/db
    ports:
      - "27017:27017"
    restart: 
      "always"
    command: mongod --bind_ip_all

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "1337:1337"
    restart: 
      "always"
    command: npm run dev